/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.util;
import edu.esprit.entities.Client;
import edu.esprit.dao.ClientDAO;
import edu.esprit.entities.Controle;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author DarkLord_666
 */
public class ajouter extends javax.swing.JFrame {

    /**
     * Creates new form ajouter
     */
    public ajouter() {
        initComponents();
        ok11.setVisible(false);
        ok22.setVisible(false);
        ok33.setVisible(false);
        ok44.setVisible(false);
        ok55.setVisible(false);
        ok66.setVisible(false);
        ok77.setVisible(false);
        //ok8.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        ok1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ok2 = new javax.swing.JLabel();
        ok4 = new javax.swing.JLabel();
        ok3 = new javax.swing.JLabel();
        ok6 = new javax.swing.JLabel();
        ok5 = new javax.swing.JLabel();
        ok7 = new javax.swing.JLabel();
        nn1 = new javax.swing.JLabel();
        nn2 = new javax.swing.JLabel();
        nn4 = new javax.swing.JLabel();
        nn3 = new javax.swing.JLabel();
        nn5 = new javax.swing.JLabel();
        nn6 = new javax.swing.JLabel();
        nn7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ok11 = new javax.swing.JLabel();
        ok22 = new javax.swing.JLabel();
        ok44 = new javax.swing.JLabel();
        ok55 = new javax.swing.JLabel();
        ok33 = new javax.swing.JLabel();
        ok66 = new javax.swing.JLabel();
        ok77 = new javax.swing.JLabel();
        nn11 = new javax.swing.JLabel();
        nn22 = new javax.swing.JLabel();
        nn33 = new javax.swing.JLabel();
        nn44 = new javax.swing.JLabel();
        nn55 = new javax.swing.JLabel();
        nn66 = new javax.swing.JLabel();
        nn77 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        jLabel3.setText("Date Naissance");

        jLabel4.setText("Adresse");

        jLabel5.setText("Email");

        jLabel6.setText("Login");

        jLabel7.setText("N°cin");

        jLabel8.setText("Mot de passe");

        jTextPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane4.setViewportView(jTextPane12);

        jTextPane5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane5KeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(jTextPane5);

        jTextPane6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane6KeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(jTextPane6);

        jTextPane8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane8KeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(jTextPane8);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quiter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane1KeyTyped(evt);
            }
        });
        jScrollPane9.setViewportView(jTextPane1);

        jScrollPane10.setViewportView(jTextPane9);

        jTextPane4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPane4KeyTyped(evt);
            }
        });
        jScrollPane11.setViewportView(jTextPane4);

        jScrollPane12.setViewportView(jTextPane10);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        ok11.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\accept.png")); // NOI18N

        ok22.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\accept.png")); // NOI18N

        ok44.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\accept.png")); // NOI18N

        ok55.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\accept.png")); // NOI18N

        ok33.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\accept.png")); // NOI18N

        ok66.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\accept.png")); // NOI18N

        ok77.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\accept.png")); // NOI18N

        nn11.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\cross.png")); // NOI18N

        nn22.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\cross.png")); // NOI18N

        nn33.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\cross.png")); // NOI18N

        nn44.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\cross.png")); // NOI18N

        nn55.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\cross.png")); // NOI18N

        nn66.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\cross.png")); // NOI18N

        nn77.setIcon(new javax.swing.ImageIcon("C:\\Users\\DarkLord_666\\Desktop\\cross.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok77)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn77)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ok7)
                                .addGap(72, 72, 72)
                                .addComponent(nn7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ok2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(ok3)
                                .addGap(72, 72, 72)
                                .addComponent(nn3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ok6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ok5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nn5)
                                    .addComponent(nn6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn44))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ok4)
                                .addGap(72, 72, 72)
                                .addComponent(nn4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok66)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn66))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nn33)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ok1)
                                        .addComponent(nn1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ok11)
                                    .addComponent(nn11))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ok22)
                                        .addComponent(nn22))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ok2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nn2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(6, 6, 6))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nn3)
                                        .addComponent(ok3))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ok4)
                                    .addComponent(nn4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nn5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(ok5)))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ok66)
                                    .addComponent(nn66))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nn6)
                                    .addComponent(ok6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nn33))
                                            .addComponent(ok33)))
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ok44)
                                            .addComponent(nn44))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(nn55)
                                                    .addComponent(ok55)))))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 7, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField1))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ok7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nn7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nn77)
                                            .addComponent(ok77))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Nom =jTextPane1.getText();
        String Prenom =jTextPane2.getText();
       
     int day=Integer.parseInt(jTextPane12.getText());
     int month=Integer.parseInt(jTextPane9.getText());
     int Year=Integer.parseInt(jTextPane10.getText());
     
    String Date_naiss=day+" / "+month +" / " +Year;
        String Adresse =jTextPane4.getText();
        String email =jTextPane5.getText();
      int cin =Integer.parseInt(jTextPane6.getText());
        String login =jTextField1.getText();
       
        String pwd =jTextPane8.getText(); 
        Client cc=new Client();
        ClientDAO dao=new ClientDAO();
   
        int num = String.valueOf(cin).length();
        int d=String.valueOf(day).length();
        //int m=String.valueOf(month).length();
                int y=String.valueOf(Year).length();
                 
        if(num==8 )
        {if(y==4  && day<32 && month<13  )
        {if(dao.findClientbylogin(login)!=null && dao.findClientbylogin(login).getLogin()==null) 
        {
      
        cc.setCin(cin);
        cc.setDate_naiss(Date_naiss);
        cc.setEmail(email);
        cc.setLogin(login);
        cc.setPwd(pwd);
        cc.setAdresse(Adresse);
        cc.setNom(Nom);
        cc.setPrenom(Prenom);
        dao.insertClient(cc);
        JOptionPane.showMessageDialog(this, "Ajout effectué avec succès");
        }
        else
        {
        JOptionPane.showMessageDialog(this, "Ajout refuser !Login Existant");
        }
        }
        else
        {
        JOptionPane.showMessageDialog(this, "Ajout refuser !Veuillez vérifier la date de naissance");
        }
        }
        else
        {
         JOptionPane.showMessageDialog(this, "Ajout refuser !Veuillez vérifier le numéro de cin");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
		

    public static boolean verifierInt(String entier) {
    boolean v = false;
    try {
    //on essaie de convertir la chaîne en nombre entier
    Integer.parseInt(entier);
    //conversion aboutie, v prend la valeur true
    v = true;
    } catch (Exception e) {
    //conversion échouée, levée d'une exception, v prend false
    v = false;
    }
    //on retourne v
    return v;
    }

	
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
 dispose();
       Gérer_Client g =new  Gérer_Client();
 g.setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextPane1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane1KeyTyped
   Controle c = new Controle();
        boolean result = c.controlestring(jTextPane1.getText());
        System.out.println("" + result);
        if (result == true) {
            nom = true;
            ok11.setVisible(true);
            nn11.setVisible(false);
        } else if (result == false) {
            nom = false;
            ok11.setVisible(false);
            nn11.setVisible(true);
        } else if (jTextPane1.getText() == null) {
            nom = false;
            ok11.setVisible(false);
            nn11.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane1KeyTyped

    private void jTextPane2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane2KeyTyped
       Controle c = new Controle();
        boolean result = c.controlestring(jTextPane2.getText());
        System.out.println("" + result);
        if (result == true) {
            prenom = true;
            ok22.setVisible(true);
            nn22.setVisible(false);
        } else if (result == false) {
            prenom = false;
            ok2.setVisible(false);
            nn2.setVisible(true);
        } else if (jTextPane2.getText() == null) {
            prenom = false;
            ok22.setVisible(false);
            nn22.setVisible(true);
        }     
    }//GEN-LAST:event_jTextPane2KeyTyped

    private void jTextPane4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane4KeyTyped
     Controle c = new Controle();
        boolean result = c.controlestring(jTextPane4.getText());
        System.out.println("" + result);
        if (result == true) {
            adresse = true;
            ok33.setVisible(true);
            nn33.setVisible(false);
        } else if (result == false) {
            adresse = false;
            ok33.setVisible(false);
            nn33.setVisible(true);
        } else if (jTextPane4.getText() == null) {
            adresse = false;
            ok33.setVisible(false);
            nn33.setVisible(true);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane4KeyTyped

    private void jTextPane6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane6KeyTyped
      Controle c = new Controle();
        boolean result = c.controlenumber(jTextPane6.getText());
        System.out.println("" + result);
        if (result == true) {
            cin = true;
            ok55.setVisible(true);
            nn55.setVisible(false);
        } else if (result == false) {
            cin = false;
            ok5.setVisible(false);
            nn5.setVisible(true);
        } else if (jTextPane6.getText() == null) {
            cin = false;
            ok55.setVisible(false);
            nn55.setVisible(true);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane6KeyTyped

    private void jTextPane5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane5KeyTyped
        Controle c = new Controle();
        boolean result = c.controlemail(jTextPane5.getText());
        System.out.println("" + result);
        if (result == true) {
            email = true;
            ok44.setVisible(true);
            nn44.setVisible(false);
        } else if (result == false) {
            email = false;
            ok44.setVisible(false);
            nn44.setVisible(true);
        } else if (jTextPane5.getText() == null) {
            email = false;
            ok44.setVisible(false);
            nn44.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextPane5KeyTyped

    private void jTextPane8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane8KeyTyped
      Controle c = new Controle();
        boolean result = c.controlestring(jTextPane8.getText());
        System.out.println("" + result);
        if (result == true) {
            mdp = true;
            ok77.setVisible(true);
            nn77.setVisible(false);
        } else if (result == false) {
            mdp = false;
            ok77.setVisible(false);
            nn77.setVisible(true);
        } else if (jTextPane8.getText() == null) {
            mdp = false;
            ok77.setVisible(false);
            nn77.setVisible(true);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane8KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
       Controle c = new Controle();
        boolean result = c.controlelogin(jTextField1.getText());
        System.out.println("" + result);
        if (result == true) {
            login = true;
            ok66.setVisible(true);
            nn66.setVisible(false);
        } else if (result == false) {
            login = false;
            ok66.setVisible(false);
            nn66.setVisible(true);
        } else if (jTextField1.getText() == null) {
            login = false;
            ok66.setVisible(false);
            nn66.setVisible(true);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ajouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    private javax.swing.JLabel nn1;
    private javax.swing.JLabel nn11;
    private javax.swing.JLabel nn2;
    private javax.swing.JLabel nn22;
    private javax.swing.JLabel nn3;
    private javax.swing.JLabel nn33;
    private javax.swing.JLabel nn4;
    private javax.swing.JLabel nn44;
    private javax.swing.JLabel nn5;
    private javax.swing.JLabel nn55;
    private javax.swing.JLabel nn6;
    private javax.swing.JLabel nn66;
    private javax.swing.JLabel nn7;
    private javax.swing.JLabel nn77;
    private javax.swing.JLabel ok1;
    private javax.swing.JLabel ok11;
    private javax.swing.JLabel ok2;
    private javax.swing.JLabel ok22;
    private javax.swing.JLabel ok3;
    private javax.swing.JLabel ok33;
    private javax.swing.JLabel ok4;
    private javax.swing.JLabel ok44;
    private javax.swing.JLabel ok5;
    private javax.swing.JLabel ok55;
    private javax.swing.JLabel ok6;
    private javax.swing.JLabel ok66;
    private javax.swing.JLabel ok7;
    private javax.swing.JLabel ok77;
    // End of variables declaration//GEN-END:variables
private javax.swing.JOptionPane jperr;
    public String message = "";
    public boolean nom = true;
    public boolean prenom = true;
    public boolean mdp = true;
    public boolean login = true;
    public boolean email = true;
    public boolean adresse = true;
     public boolean cin = true;
}
